# Generated by Django 6.0.2 on 2026-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobuyjob',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional end date to stop the job', null=True),
        ),
    ]
