# Generated by Django 6.0.2 on 2026-02-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_autobuyjob_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobuyjob',
            name='quote_currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USDC', 'USDC'), ('USD', 'USD')], default='USDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='autobuyjob',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount to spend per run (in quote currency, e.g. USDT)', max_digits=20),
        ),
    ]
