# Generated by Django 6.0.2 on 2026-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autobuyjob_quote_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobuyjob',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='autobuyjob',
            name='last_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('warning', 'Warning'), ('failure', 'Failure')], max_length=20, null=True),
        ),
    ]
