# Generated by Django 6.0.2 on 2026-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_autobuyjob_last_error_message_autobuyjob_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='job_name',
            field=models.CharField(default='Unknown Job', help_text='Snapshot of job name at time of trade', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='order_type',
            field=models.CharField(default='market', max_length=20),
        ),
    ]
