# Generated by Django 6.0.2 on 2026-02-20 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polar_customer_id', models.CharField(blank=True, max_length=255)),
                ('polar_subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(default='inactive', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('manual_access_granted', models.BooleanField(default=False, help_text='Grant full access without subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
