# Generated by Django 6.0.2 on 2026-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobuyjob',
            name='name',
            field=models.CharField(default='Moondrip Job', max_length=100),
        ),
    ]
