# Generated by Django 6.0.2 on 2026-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_trade_failed',
            field=models.BooleanField(default=True, help_text='Email alert when a trade fails'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_trade_skipped_paused',
            field=models.BooleanField(default=True, help_text='Email alert when a trade is skipped because the job was paused'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_trade_success',
            field=models.BooleanField(default=True, help_text='Email alert when a trade executes successfully'),
        ),
        migrations.AlterField(
            model_name='autobuyjob',
            name='name',
            field=models.CharField(default='Moondrip Job', max_length=100),
        ),
    ]
