# Generated by Django 6.0.2 on 2026-02-24 07:58

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_autobuyjob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='allow_google_oauth',
            field=models.BooleanField(default=True, help_text='Allow users to login or link accounts via Google.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='require_2fa_globally',
            field=models.BooleanField(default=False, help_text='Force all users to configure and use 2FA.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='polar_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=core.fields.EncryptedCharField(blank=True, help_text="User's TOTP secret for 2FA", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('polar_product_id', models.CharField(blank=True, help_text='Assign to this group if user has active subscription to this Polar product.', max_length=255)),
                ('referral_code', models.CharField(blank=True, help_text='Assign to this group if user registered with this referral code (e.g. Toobit).', max_length=100)),
                ('allowed_exchanges', models.ManyToManyField(blank=True, related_name='user_groups', to='core.supportedexchange')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.usergroup'),
        ),
    ]
