# Generated by Django 6.0.2 on 2026-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_notify_trade_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobuyjob',
            name='limit_order_timeout_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes to wait before canceling and replacing unfilled limit orders'),
        ),
        migrations.AddField(
            model_name='autobuyjob',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit (Maker - Lower Fees)'), ('market', 'Market (Taker)')], default='limit', help_text='Maker limit orders sit on the order book and capture lower exchange fees', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit (Maker)'), ('market', 'Market (Taker)')], default='market', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('open', 'Open'), ('canceled', 'Canceled'), ('partially_filled', 'Partially Filled')], default='completed', max_length=20),
        ),
    ]
