# Generated by Django 6.0.2 on 2026-09-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_autobuyjob_limit_order_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobuyjob',
            name='limit_order_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes to wait before canceling and replacing unfilled limit orders'),
        ),
    ]
