# Generated by Django 6.0.2 on 2026-02-26 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appsettings_allow_google_oauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='allow_google_oauth',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='require_2fa_globally',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='polar_product_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_profiles', to='core.supportedexchange'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('none', 'None'), ('paid', 'Paid'), ('affiliate', 'Affiliate')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
