# Generated by Django 6.0.2 on 2026-02-27 18:06

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_userprofile_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='allow_google_oauth',
            field=models.BooleanField(default=True, help_text='Allow users to login or link accounts via Google.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='require_2fa_globally',
            field=models.BooleanField(default=False, help_text='Force all users to configure and use 2FA.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=core.fields.EncryptedCharField(blank=True, help_text="User's TOTP secret for 2FA", max_length=255, null=True),
        ),
    ]
