# Generated by Django 6.0.2 on 2026-09-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_existing_timeout_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_job_summary',
            field=models.BooleanField(default=True, help_text='Email summary whenever an automated DCA job completes its run'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_trade_individual',
            field=models.BooleanField(default=False, help_text='Email notification for each individual trade or order fill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_pricing_account',
            field=models.ForeignKey(blank=True, help_text='Preferred active exchange account for live market prices and 24h calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_profiles', to='core.exchangeaccount'),
        ),
    ]
